### ISSUE TITLE
Tile type 'B' and 'b' not defined in Super Mario Bros / Processed levels

### ISSUE THREAD

**Issue by lucadiliello** [TheVGLC/TheVGLC#2]
Tiles of type 'B' and 'b' are not defined in `smb.json`, but are required by some levels.

**Comment by santiontanon** [comment]
Hi! If you are referring to the maps in the "Super Mario Bros" folder, "B" and "b" are not used in the maps in the "processed" folder, right? They do appear in the "Multi-layer" folder, but for maps in that folder you have the "smb-multi-layer.json" file that defines additional needed types.

**Comment by lucadiliello** [comment]
Hi :)
The `mario-7-1.txt` level contains `B` and `b` tiles.

**Comment by santiontanon** [comment]
Oh, I missed that one. Those are cannons! Sam and Adam might know better, but I think the .json file should be extended with these two lines there (I took these lines from the multilayered version, where they are "C" and "c", but I think it should be the same):

    "B" : ["Cannon top","cannon","solid","hazard"],
    "b" : ["Cannon bottom","cannon","solid"]

Sam? Adam?

**Comment by lucadiliello** [comment]
Thank you for the help! I will use your solution at the moment, seems working fine.
